//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoBalance
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public string username { get; set; }
        public string transaction_id { get; set; }
        public string crypto_coin { get; set; }
        public double market_price { get; set; }
        public double amount { get; set; }
        public double cryto_total { get; set; }
    }
}
